---
- hosts: all
  become: yes
  tasks:
  - name:
    ping:

  - name: i want to intsall webserver on ubuntu ansible nodes
    apt:
     name: apache2
     state: present

  - name: i want to install tree on ubuntu
    apt:
     name: tree
     state: present

